[package]
name = "tagpad-imgui"
version.workspace = true
edition.workspace = true
license-file.workspace = true
publish = false

[dependencies]
tagpad-core = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
imgui = "0.12"
imgui-winit-support = "0.13"
imgui-glow-renderer = "0.13"
glow = "0.14"
winit = "0.30"
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.13"

[lints]
workspace = true
